// app/layout.js (or layout.tsx for TypeScript)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// Load Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Metadata used by App Router (no need to manually add link for favicon)
export const metadata = {
  title: "Being Instruments",
  description: "Generated by create next app",
  icons: {
    icon: "/inkarpCircle.png", // Must be in /public
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {/* Navbar */}
        <nav className="p-4 bg-gray-300 text-black flex gap-4">
          <Link className="hover:text-[#E63946]" href="/one">Home 1</Link>
          <Link className="hover:text-[#E63946]" href="/three">Home 3</Link>
          <Link className="hover:text-[#E63946]" href="/five">Home 5</Link>
        </nav>

        {/* Main Content */}
        {children}
      </body>
    </html>
  );
}
