import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Being Instruments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-gray-300  text-black flex gap-4">
          <Link className="hover:text-[#E63946]" href="/one">Home 1</Link>
          {/* <Link className="hover:text-[#E63946]" href="/two">Home 2</Link> */}
          <Link className="hover:text-[#E63946]" href="/three">Home 3</Link>
          <Link className="hover:text-[#E63946]" href="/five">Home 5</Link>
          {/* <Link className="hover:text-[#E63946]" href="/four">Home 4</Link> */}

        </nav>
        {children}
      </body>
    </html>
  );
}
